### ISSUE TITLE
Gulp-install fails silently with more than 16 package.json files

### ISSUE THREAD

**Issue by cyberixae** [slushjs/gulp-install#38] opened 2016-04-25 17:08 UTC
I am working on a Serverless project that has lots of separately deployable components. Each of these components has their own package.json file. I created a gulp task that uses gulp-install to install dependencies for all of the modules in one go. However this only worked until we reached the magic limit of 17 package.json files. When this happens gulp-install will stop installing packages but will not produce any error message to indicate that something went wrong.

**Comment by cyberixae** [comment] 2016-04-25 17:11
I believe the problem is somehow related to the ​_high water mark_​ of 16 items in Node streams.

**Comment by cyberixae** [comment] 2016-04-26 17:46
I created an example project for testing. See https://github.com/cyberixae/gulp-install-test

**Comment by davidchase** [comment] 2016-06-06 04:36
@cyberixae it is related to `high water mark​ of 16` , `gulp-install` uses `through2` [#L30](https://github.com/slushjs/gulp-install/blob/master/index.js#L30) in object-mode which sets the hwm to 16 for the default.. the reason you cannot process more than 17 files is because you are adding files readable part of `through2` module and its hitting the buffer limit. based on your test repo you need to `drain` the readable part by doing something like `pipe(install()).pipe(...)` then you can process more than aforementioned file limit

**Comment by cyberixae** [comment] 2016-06-06 11:34
Actually, we ended up using the Serverless AutoInstall Plugin, so this bug thread is no longer relevant for me. The plugin can be found at https://github.com/kennu/serverless-plugin-autoinstall if someone else has the same use case.

**Comment by sloppylopez** [comment] 2016-06-27 21:37
Hi, I think i am facing the same issue here, the problem is that I am not using Serverless so I cannot avoid the problem so easily, surprisingly for me, If i use gulp-install 0.4.0 it works like a charm...

**Comment by joakimbeng** [comment] 2017-03-23 07:26
Sorry for the great delay!
A fix for this is on its way...

**Closed** 2017-03-23 07:47 UTC
